-- Unable to render TABLE DDL for object ANKIT.CLASS with DBMS_METADATA attempting internal generator.
CREATE TABLE CLASS 
(
  CLASSID VARCHAR2(20 BYTE) NOT NULL 
, SCHEDULEID VARCHAR2(20 BYTE) 
, CLASSBUILDING VARCHAR2(25 BYTE) NOT NULL 
, CLASSROOM VARCHAR2(25 BYTE) NOT NULL 
, DEPTNO NUMBER 
, INSTRUCTORID VARCHAR2(20 BYTE) 
, SEMESTER VARCHAR2(6 BYTE) DEFAULT 'I' 
, YEAR DATE DEFAULT sysdate 
, CONSTRAINT CLASS_CLASSID_PK PRIMARY KEY 
  (
    CLASSID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLASS_CLASSID_PK ON CLASS (CLASSID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE CLASS
ADD CONSTRAINT CLASS_DNO_FK FOREIGN KEY
(
  DEPTNO 
)
REFERENCES DEPARTMENT
(
  DEPTNO 
)
ENABLE
ALTER TABLE CLASS
ADD CONSTRAINT CLASS_INSTID_FK FOREIGN KEY
(
  SCHEDULEID 
)
REFERENCES INSTRUCTOR
(
  INSTRUCTORID 
)
ENABLE
ALTER TABLE CLASS
ADD CONSTRAINT CLASS_SCHEDID_FK FOREIGN KEY
(
  SCHEDULEID 
)
REFERENCES SCHEDULE_TYPE
(
  SCHEDULEID 
)
ENABLE
