-- Unable to render TABLE DDL for object ANKIT.CLASSLOCATION with DBMS_METADATA attempting internal generator.
CREATE TABLE CLASSLOCATION 
(
  CLASSBUILDING VARCHAR2(25 BYTE) NOT NULL 
, CLASSROOM VARCHAR2(25 BYTE) NOT NULL 
, SEATINGCAPACITY VARCHAR2(3 BYTE) DEFAULT 100 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
