-- Unable to render TABLE DDL for object ANKIT.COURSE with DBMS_METADATA attempting internal generator.
CREATE TABLE COURSE 
(
  COURSEID VARCHAR2(5 BYTE) NOT NULL 
, DEPTNO NUMBER NOT NULL 
, TITLE VARCHAR2(75 BYTE) NOT NULL 
, DESCRIPTION VARCHAR2(200 BYTE) NOT NULL 
, ADDITIONAL_FEES NUMBER(9, 2) 
, CONSTRAINT COURSE_CIDDNO_PK PRIMARY KEY 
  (
    COURSEID 
  , DEPTNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COURSE_CIDDNO_PK ON COURSE (COURSEID ASC, DEPTNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE COURSE
ADD CONSTRAINT SYS_C0036094 CHECK 
(additional_fees>0)
ENABLEALTER TABLE COURSE
ADD CONSTRAINT COURSE_DNO_FK FOREIGN KEY
(
  DEPTNO 
)
REFERENCES DEPARTMENT
(
  DEPTNO 
)
ENABLE
