-- Unable to render TABLE DDL for object ANKIT.EMPLOYEE with DBMS_METADATA attempting internal generator.
CREATE TABLE EMPLOYEE 
(
  EMPNO NUMBER NOT NULL 
, ENAME VARCHAR2(30 BYTE) NOT NULL 
, JOB VARCHAR2(12 BYTE) 
, MGR NUMBER 
, HIREDATE DATE 
, SALARY NUMBER(7, 2) 
, COMM NUMBER(7, 2) 
, DEPTNO NUMBER 
, GENDER VARCHAR2(12 BYTE) 
, CONSTRAINT EMP_ENO_PK PRIMARY KEY 
  (
    EMPNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMP_ENO_PK ON EMPLOYEE (EMPNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE EMPLOYEE
ADD CONSTRAINT SYS_C0036076 CHECK 
(salary>0)
ENABLE
ALTER TABLE EMPLOYEE
ADD CONSTRAINT SYS_C0036077 CHECK 
(gender = 'MALE' or Gender = 'FEMALE')
ENABLEALTER TABLE EMPLOYEE
ADD CONSTRAINT EMP_MGR_FK FOREIGN KEY
(
  MGR 
)
REFERENCES EMPLOYEE
(
  EMPNO 
)
ENABLE
