-- QUERY 1
SELECT LAST_NAME
  || ', '
  || JOB_ID AS "EMPLOYEE AND TITLE"
FROM EMPLOYEES;
/
-- QUERY 2
SELECT EMPLOYEE_ID
  || ', '
  || FIRST_NAME
  || ', '
  || LAST_NAME
  || ', '
  || EMAIL
  || ', '
  || PHONE_NUMBER
  || ', '
  || HIRE_DATE
  || ', '
  || JOB_ID
  || ', '
  || SALARY
  || ', '
  || COMMISSION_PCT
  || ', '
  || MANAGER_ID
  || ', '
  || DEPARTMENT_ID AS "THE_OUTPUT"
FROM EMPLOYEES;
/
-- QUERY 3
SELECT LAST_NAME,
  SALARY
FROM EMPLOYEES
WHERE SALARY NOT BETWEEN 5000 AND 12000;
/
-- QUERY 4
SELECT LAST_NAME,
  JOB_ID,
  HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN TO_DATE('20-FEB-1998','DD-MON-YYYY') AND TO_DATE('01-MAY-1998','DD-MON-YYYY')
ORDER BY HIRE_DATE ASC;
/
-- QUERY 5
SELECT LAST_NAME,
  DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN ( 20, 50 )
ORDER BY LAST_NAME;
/
-- QUERY 6
SELECT E.LAST_NAME,
  J.JOB_TITLE
FROM EMPLOYEES E NATURAL
JOIN JOBS J
WHERE E.MANAGER_ID IS NULL;
/
-- QUERY 7
SELECT LAST_NAME,
  SALARY,
  COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC,
  COMMISSION_PCT DESC;
/
-- QUERY 8
SELECT EMPLOYEE_ID,
  LAST_NAME,
  SALARY,
  ROUND(SALARY + (0.15 * SALARY) ) AS "NEW SALARY"
FROM EMPLOYEES;
/
-- QUERY 9
SELECT EMPLOYEE_ID,
  LAST_NAME,
  SALARY,
  ROUND(SALARY + (0.15 * SALARY) )          AS "NEW SALARY",
  ROUND(SALARY + (0.15 * SALARY) ) - SALARY AS INCREASE
FROM EMPLOYEES;
/
-- QUERY 10
SELECT INITCAP(LAST_NAME) AS "LAST NAME",
  LENGTH(LAST_NAME)       AS "NAME LENGTH"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'J%'
OR LAST_NAME LIKE 'A%'
OR LAST_NAME LIKE 'M%';
/
-- QUERY 11
SELECT UNIQUE J.JOB_TITLE,
  L.CITY
FROM JOBS J
JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID
JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L
ON L.LOCATION_ID      = D.LOCATION_ID
WHERE E.DEPARTMENT_ID = 80;
/
-- QUERY 12
SELECT E.LAST_NAME ,
  D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.LAST_NAME LIKE '%A%';
/
-- QUERY 13
SELECT E.LAST_NAME,
  J.JOB_TITLE,
  E.DEPARTMENT_ID,
  D.DEPARTMENT_NAME
FROM JOBS J
JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID
JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN LOCATIONS L
ON L.LOCATION_ID  = D.LOCATION_ID
WHERE UPPER(CITY) = 'TORONTO';
/
-- QUERY 14
SELECT E.DEPARTMENT_ID DEPARTMENT,
  E.FIRST_NAME
  ||' '
  ||E.LAST_NAME "EMPLOYEE NAME",
  C.FIRST_NAME
  ||' '
  ||C.LAST_NAME "COLLEAGUE NAME"
FROM EMPLOYEES E
JOIN EMPLOYEES C
ON (E.DEPARTMENT_ID  = C.DEPARTMENT_ID)
WHERE E.EMPLOYEE_ID <> C.EMPLOYEE_ID
ORDER BY E.DEPARTMENT_ID,
  E.FIRST_NAME,
  C.FIRST_NAME ;
/
-- QUERY 15
SELECT E.FIRST_NAME
  ||' '
  ||E.LAST_NAME AS "EMPLOYEE",
  E.HIRE_DATE   AS "EMP HIRED",
  M.FIRST_NAME
  ||' '
  ||M.LAST_NAME AS "MANAGER" ,
  M.HIRE_DATE   AS "MGR HIRED"
FROM EMPLOYEES E
JOIN EMPLOYEES M
ON E.MANAGER_ID   = M.EMPLOYEE_ID
WHERE E.HIRE_DATE < M.HIRE_DATE;
/
-- QUERY 16
SELECT ROUND(MAX(SALARY)) AS MAXIMUM,
  ROUND(MIN(SALARY))      AS MINIMUM,
  ROUND(SUM(SALARY))      AS SUM,
  ROUND(AVG(SALARY))      AS AVERAGE
FROM EMPLOYEES;
/
-- QUERY 17
SELECT COUNT(DISTINCT(MANAGER_ID)) FROM EMPLOYEES;
/
-- QUERY 18
SELECT COUNT(*),
  EXTRACT(YEAR FROM HIRE_DATE)
FROM EMPLOYEES
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
HAVING EXTRACT(YEAR FROM HIRE_DATE) IN (1195,1996,1997,1998);
/
-- QUERY 19
SELECT J.JOB_TITLE AS JOB,
  SUM(SALARY) "JOB SALARY",
  SUM(DECODE (DEPARTMENT_ID, 20, SALARY)) "DEPT 20 SAL",
  SUM(DECODE (DEPARTMENT_ID, 50, SALARY)) "DEPT 50 SAL",
  SUM(DECODE (DEPARTMENT_ID, 80, SALARY)) "DEPT 80 SAL",
  SUM(DECODE (DEPARTMENT_ID, 90, SALARY)) "DEPT 90 SAL"
FROM EMPLOYEES E
JOIN JOBS J
ON J.JOB_ID = E.JOB_ID
GROUP BY J.JOB_TITLE;
/
-- QUERY 20
SELECT EMPLOYEE_ID,
  LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN
  (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%'
  )
ORDER BY EMPLOYEE_ID;
/
-- QUERY 21
SELECT LAST_NAME,
  DEPARTMENT_ID,
  SALARY
FROM EMPLOYEES
WHERE (SALARY, DEPARTMENT_ID) IN
  (SELECT SALARY,
    DEPARTMENT_ID
  FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NOT NULL
  );
/
-- QUERY 22
SELECT LAST_NAME,
  HIRE_DATE,
  SALARY
FROM EMPLOYEES
WHERE (SALARY , NVL(COMMISSION_PCT,0)) IN
  (SELECT SALARY ,
    NVL(COMMISSION_PCT,0)
  FROM EMPLOYEES
  WHERE UPPER(LAST_NAME) = 'KOCHHAR'
  )
AND UPPER(LAST_NAME) != 'KOCHHAR';
/
-- QUERY 23
SELECT E.LAST_NAME "EMP NAME",
  E.SALARY "SALARY",
  E.DEPARTMENT_ID "DEPARTMENT ID",
  ROUND(AVG(A.SALARY),1) "DEPARTMENT AVERAGE SAL"
FROM EMPLOYEES E
JOIN EMPLOYEES A
ON E.DEPARTMENT_ID = A.DEPARTMENT_ID
WHERE E.SALARY     >
  (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID
  )
GROUP BY E.LAST_NAME,
  E.SALARY,
  E.DEPARTMENT_ID
ORDER BY AVG(A.SALARY);
/