-- Unable to render TABLE DDL for object ANKIT.STUDENTSCHEDULE with DBMS_METADATA attempting internal generator.
CREATE TABLE STUDENTSCHEDULE 
(
  STUDENTID VARCHAR2(20 BYTE) 
, CLASSID VARCHAR2(20 BYTE) 
, GRADE VARCHAR2(2 BYTE) 
, GRADEASSIGNED DATE DEFAULT sysdate 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESSALTER TABLE STUDENTSCHEDULE
ADD CONSTRAINT SYS_C0036112 CHECK 
(grade in ('A','A+','B','B+','C','C+'))
ENABLE
