-- Unable to render TABLE DDL for object ANKIT.STUDENT with DBMS_METADATA attempting internal generator.
CREATE TABLE STUDENT 
(
  STUDENTID VARCHAR2(20 BYTE) NOT NULL 
, FIRSTNAME VARCHAR2(21 BYTE) NOT NULL 
, LASTNAME VARCHAR2(21 BYTE) NOT NULL 
, DATE_OF_BIRTH DATE 
, ADDRESS VARCHAR2(300 BYTE) 
, CITY VARCHAR2(20 BYTE) NOT NULL 
, STATE VARCHAR2(12 BYTE) NOT NULL 
, ZIPCODE VARCHAR2(9 BYTE) NOT NULL 
, TELEPHONE VARCHAR2(10 BYTE) DEFAULT 'NA' 
, FAX VARCHAR2(10 BYTE) DEFAULT 'NA' 
, EMAIL VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT STUD_STUDID_PK PRIMARY KEY 
  (
    STUDENTID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX STUD_STUDID_PK ON STUDENT (STUDENTID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
